name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.2.0
      with:
        changelog_regex: '/CHANGES.md'
        customPrMessage: 'Make sure to keep CHANGES.md up to date!'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.0.1

  build-ios:
    name: Build and test iOS target
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.1.app && /usr/bin/xcodebuild -version
    - name: Prepare Developer.xcconfig
      run: cp EduVPN/Config/Developer.xcconfig.eduvpn-template EduVPN/Config/Developer.xcconfig
    - name: Prepare config.json
      run: cp EduVPN/Config/config-eduvpn_dev.json EduVPN/Config/config.json
    - name: Prepare assets
      run: cp -r EduVPN/Config/Assets-EduVPN.xcassets EduVPN/Resources/Assets.xcassets
    - name: Run tests on iOS 13
      run: xcodebuild test -scheme EduVPN -workspace EduVPN.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' -skip-testing EduVPN_UITests_iOS | xcpretty && exit ${PIPESTATUS[0]}
#    - name: Run tests on iOS 12
#      run: xcodebuild test -scheme EduVPN -workspace EduVPN.xcworkspace -destination 'platform=iOS Simulator,name=iPhone X,OS=12.4' | xcpretty && exit ${PIPESTATUS[0]}

  build-macos:
    name: Build macOS target
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.1.app
    - name: Prepare Developer-macos.xcconfig
      run: cp EduVPN-macOS/Config/Developer-macos.xcconfig.eduvpn-template EduVPN-macOS/Config/Developer-macos.xcconfig
    - name: Prepare config.json
      run: cp EduVPN-macOS/Config/config-eduvpn_dev.json EduVPN-macOS/Config/config.json
    - name: Prepare assets
      run: cp -r EduVPN-macOS/Config/Assets-eduVPN.xcassets EduVPN/Resources/Assets-macOS.xcassets
    - name: Run MacOS build
      run: xcodebuild build -scheme EduVPN-macOS -workspace EduVPN.xcworkspace -destination 'platform=macOS' CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
